version: "3"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - AIRFLOW_HOME=/home/airflow
    - AIRFLOW__CORE_dags_folder=/home/airflow/dags
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./output:/home/airflow/output
    - ./dags:/home/airflow/dags
    - ./dbt:/home/airflow/dbt
    - ./plugins:/home/airflow/plugins
    - ./logs:/home/airflow/logs
    - ./jobs/:/home/airflow/jobs
  depends_on:
    - postgres
  networks:
    - hadoop_network

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - hadoop_network

  # airflow-init:
  #   <<: *airflow-common
  #   container_name: airflow_init
  #   entrypoint: /bin/bash
  #   command:
  #     - -c
  #     - airflow db migrate
  #   restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow webserver"
    #command: bash -c "airflow webserver"
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname John --lastname Doe --role Admin --email admin@gmail.com --password admin && airflow scheduler"
    container_name: airflow_scheduler
    restart: always

networks:
  hadoop_network:
    name: hadoop_network
    external: true
